/** Plain-language meaning of each policy decision code from packages/agent/src/policyClient.ts. */
export const REASON_TEXT:Record<string,string>={
  OK:'Within every rule: the agent may sign this payment.',
  INVALID_AMOUNT:'Enter an amount greater than zero, in raw units.',
  SOURCE_UNAVAILABLE:'A required live source could not be read, so the agent refuses rather than guess.',
  NO_POLICY:'No policy contract is configured, so the agent will not pay.',
  HCS_NOT_READY:'The agent\'s HCS profile is not set up yet.',
  IDENTITY_MISSING:'The agent\'s ERC-8004 identity is not registered yet.',
  AGENT_KEY_INACTIVE:'The guardian removed the agent\'s key, so it can no longer sign.',
  PAUSED:'The guardian paused the policy; the agent refuses every payment until it is unpaused.',
  ASSET_NOT_ALLOWED:'The policy does not allow spending this token.',
  OVER_TX_CAP:'The amount is above the per-transaction cap.',
  OVER_DAY_CAP:'This payment would take today\'s spending above the daily cap.',
  INSUFFICIENT_BALANCE:'The agent does not hold enough of this token to pay this amount.',
  AGENT_BUSY:'The agent is already working on a task; wait for it to finish.',
  OPERATION_IN_PROGRESS:'The agent is busy recording a swap; try again in a few seconds.',
  SCHEDULE_TOO_SOON:'Pick a time at least two minutes from now.',
  SCHEDULE_TOO_LATE:'Pick a time within the next seven days.',
  INVALID_SCHEDULE_TIME:'Pick a valid date and time.',
  DEX_NO_LIQUIDITY:'The testnet pool has no liquidity for this swap.',
  DEX_QUOTE_REVERTED:'The testnet pool refused to quote this swap.',
  SWAP_UNCONFIRMED:'The mirror did not show the expected token movement, so the swap is not reported as done.',
  SCHEDULE_NOT_PENDING:'This scheduled swap has already executed, expired or been cancelled.',
  SETUP_REQUIRED:'Finish agent setup first.',
  API_UNAVAILABLE:'The local API did not answer; check that npm run dev is running.',
};
