/** Plain-language meaning of each policy decision code from packages/agent/src/policyClient.ts. */
export const REASON_TEXT:Record<string,string>={
  OK:'Within every rule: the agent may sign this payment.',
  INVALID_AMOUNT:'Enter an amount greater than zero, in raw units.',
  SOURCE_UNAVAILABLE:'A required live source could not be read, so the agent refuses rather than guess.',
  NO_POLICY:'No policy contract is configured, so the agent will not pay.',
  HCS_NOT_READY:'The agent\'s HCS profile is not set up yet.',
  IDENTITY_MISSING:'The agent\'s ERC-8004 identity is not registered yet.',
  AGENT_KEY_INACTIVE:'The guardian removed the agent\'s key, so it can no longer sign.',
  PAUSED:'The guardian paused the policy; the agent refuses every payment until it is unpaused.',
  ASSET_NOT_ALLOWED:'The policy does not allow spending this token.',
  OVER_TX_CAP:'The amount is above the per-transaction cap.',
  OVER_DAY_CAP:'This payment would take today\'s spending above the daily cap.',
  INSUFFICIENT_BALANCE:'The agent does not hold enough of this token to pay this amount.',
  AGENT_BUSY:'The agent is already working on a task; wait for it to finish.',
  OPERATION_IN_PROGRESS:'The agent is busy recording a swap; try again in a few seconds.',
  SCHEDULE_TOO_SOON:'Pick a time at least two minutes from now.',
  SCHEDULE_TOO_LATE:'Pick a time within the next seven days.',
  INVALID_SCHEDULE_TIME:'Pick a valid date and time.',
  DEX_NO_LIQUIDITY:'The testnet pool has no liquidity for this swap.',
  DEX_QUOTE_REVERTED:'The testnet pool refused to quote this swap.',
  SWAP_UNCONFIRMED:'The mirror did not show the expected token movement, so the swap is not reported as done.',
  SCHEDULE_NOT_PENDING:'This scheduled swap has already executed, expired or been cancelled.',
  SETUP_REQUIRED:'Finish agent setup first.',
  INSUFFICIENT_PAYER_BALANCE:'When Hedera ran the swap, the agent account did not have enough HBAR to pay the network fee. No tokens moved and the amount went back to the daily limit.',
  SCHEDULE_EXPIRED:'The schedule reached its time without executing.',
  CANCELLED_FROM_DASHBOARD:'Cancelled from the dashboard before it executed.',
  CANCELLED_BY_AGENT:'Cancelled by the agent before it executed.',
  GAS_PRICE_UNAVAILABLE:'The current gas price could not be read, so the agent refuses rather than guess its fees.',
  NO_HEDERA_USDC_OPTION:'The service does not accept USDC on Hedera testnet, so the agent will not pay it.',
  PRICE_ABOVE_LIMIT:'The service asks more than the highest price you set.',
  SELLER_NOT_VERIFIED:'The seller is not the verified ERC-8004 agent you named, or it is paid at a different account.',
  PAYMENT_SELF_TRANSFER:'The service would pay the agent itself; use a service run by another agent.',
  PAYMENT_NOT_SETTLED:'The service did not submit the payment, so no money moved and the amount went back to the daily limit.',
  PAYMENT_UNCONFIRMED:'The payment could not be confirmed on the mirror yet; it stays counted against the daily limit.',
  INVALID_SERVICE_URL:'Use an https URL, or http only to this machine.',
  SERVICE_UNREACHABLE:'The service did not answer.',
  TOKEN_NOT_ASSOCIATED:'The agent account is not associated with this token, so it holds none.',
  INFERENCE_NOT_CONFIGURED:'The seller has not configured an LLM provider, so its endpoint charges nothing and answers 503.',
  INFERENCE_EMPTY_ANSWER:'The model returned no text, for example a reasoning model that ran out of output tokens. Nobody was charged.',
  MISSED:'The agent runtime was not running when this payment was due, so it was skipped rather than made late.',
  PAID:'Paid, confirmed on the mirror and recorded on HCS.',
  INVALID_REPEAT:'A repeating payment needs both an interval and a number of payments.',
  INVALID_PAYMENT_JOB:'Check the URL, price, time and repeat settings.',
  API_UNAVAILABLE:'The local API did not answer; check that npm run dev is running.',
};
